name: rasusa
description: Randomly subsample sequencing reads to a specified coverage using `rasusa <https://github.com/mbhall88/rasusa>`_.
container: docker://mbhall88/rasusa:0.3.0
authors:
  - Michael Hall
